name: 白果园
description: 有时欣喜若狂，有时感觉不到生长
meta_description: "自留地"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: 'https://bulgerxie.github.io'
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://bulgerxie.github.io/'
author:         'bulger'
